const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link = (url,label) => url ? `<a href="${esc(url)}" target="_blank" rel="noreferrer">${esc(label)}</a>` : esc(label);
export function render(report) {
  const card=a=>`<article data-company="${esc(a.company.toLowerCase())}" data-action="${esc(a.next_action)}">
    <div class="eyebrow">${esc(a.next_action.replaceAll('-',' '))}</div><h2>${esc(a.company)}</h2>
    <p>${link(a.website,'Website / directory')} · ${a.hiring.confirmed_openings} confirmed openings · ${a.hiring.listed_openings} recent listings</p>
    <div class="columns"><section><h3>Sponsorship</h3><p>Interest: ${esc(a.sponsorship.intent)} · ${esc(a.sponsorship.status)}</p>
    ${a.sponsorship.routes.map(r=>`<p>${esc(r.name||r.function)} — ${r.kind==='email'?esc(r.value):link(r.value,'Professional route')}<br><small>${link(r.source_url,'Source')} · ${esc(r.checked_at.slice(0,10))} · recipient approval pending</small></p>`).join('')||'<p>No reviewed sponsorship contact yet.</p>'}</section>
    <section><h3>Hiring</h3><p>${a.hiring.routes.length} reviewed hiring routes. Candidate recommendations require a separate fit review.</p>
    ${a.hiring.routes.map(r=>`<p>${esc(r.name||r.function)} — ${r.kind==='email'?esc(r.value):link(r.value,'Professional route')}<br><small>${link(r.source_url,'Source')} · ${esc(r.checked_at.slice(0,10))} · recipient approval pending</small></p>`).join('')}
    ${a.hiring.candidate_matches.map(m=>`<details><summary>${esc(m.role_title)} ↔ ${esc(m.candidate)}</summary><p>${esc(m.availability)} · ${link(m.role_url,'Job source')} · ${link(m.public_url,'Public assessment')}</p><p class="limits">${link(m.availability_source_url,'Availability source')} · Checked ${esc(m.availability_checked_at??'not independently checked')}</p>${(m.alternate_sources??[]).map(s=>`<p class="limits">${link(s.url,'Original listing')} · ${esc(s.collected_at)}</p>`).join('')}
      ${m.reasons.map(r=>`<p><b>${esc(r.topic)}</b><br>${esc(r.job_excerpt)}<br><small>Evidence: ${esc(r.evidence_ids.join(', '))}</small></p>${r.work.map(w=>`<p>${esc(w.label)} · ${esc(w.delivery_state)}<br>${esc(w.summary)}<br><small>Execution: ${esc(w.authorship)} · verification: ${esc(w.verification_mode)}</small></p>`).join('')}`).join('')}
      <p class="limits">${m.limits.map(esc).join('<br>')}</p></details>`).join('')||'<p>No consented work match established.</p>'}</section></div>
    <div class="columns">${a.drafts.map(d=>`<section><h3>${esc(d.stage.replaceAll('-',' '))}</h3><p><b>${esc(d.subject)}</b></p><pre>${esc(d.body)}</pre><button type="button" class="copy">Copy draft</button>${d.prerequisites?`<p class="limits">Before follow-up: ${d.prerequisites.map(esc).join(' · ')}</p>`:''}</section>`).join('')}</div>
    <p class="limits">${a.blockers.map(b=>esc(b.replaceAll('-',' '))).join(' · ')}</p></article>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Organized AI · Sponsor & hiring review</title>
  <style>:root{color-scheme:dark;--bg:#141413;--panel:#1c1c1a;--ink:#f5f2e9;--muted:#b4b1a7;--yellow:#f2c000}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:48px 28px}header{border-bottom:1px solid #444;padding-bottom:30px}h1{font-size:clamp(36px,5vw,64px);line-height:1.05;max-width:880px;letter-spacing:-2px}h1 span,a{color:var(--yellow)}h2{font-size:30px;margin:6px 0}h3{font-size:17px}.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:12px;color:var(--yellow)}.lede{max-width:850px;color:var(--muted)}.stats{display:flex;flex-wrap:wrap;gap:24px}.stats b{display:block;font-size:30px;color:var(--yellow)}.toolbar{display:flex;gap:12px;margin:30px 0;flex-wrap:wrap}input,select,button{background:var(--panel);color:var(--ink);border:1px solid #666;padding:12px;border-radius:6px;font:inherit}input{flex:1;min-width:230px}button{cursor:pointer}button:hover{border-color:var(--yellow)}article{border:1px solid #444;border-radius:12px;background:var(--panel);padding:28px;margin:24px 0}.columns{display:grid;grid-template-columns:1fr 1fr;gap:28px}.columns>section{min-width:0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.7 system-ui,sans-serif;background:#121211;border-radius:6px;padding:18px}small,.limits{color:var(--muted);font-size:12px}details{border-top:1px solid #444;padding:12px 0}summary{cursor:pointer}a{overflow-wrap:anywhere}article[hidden]{display:none}@media(max-width:760px){.columns{grid-template-columns:1fr}main{padding:24px 16px}article{padding:20px}h1{letter-spacing:-1px}}</style></head>
  <body><main><header><div class="eyebrow">Organized AI // Private campaign review</div><h1>Sponsor the community.<br><span>Discover proven work.</span></h1>
  <p class="lede">Sponsorship introductions followed by relevant hiring conversations. Review the contact, job source and assessment evidence together. Drafts only — nothing here sends messages or enrolls contacts.</p>
  <p class="limits">Snapshot ${esc(report.generated_at)} · ${esc(report.campaign.id)} · outreach paused</p>
  <div class="stats"><div><b>${report.counts.companies}</b>Companies</div><div><b>${report.counts.roles}</b>Role records</div><div><b>${report.counts.reviewed_routes}</b>Sponsor routes</div><div><b>${report.counts.specific_followups}</b>Candidate-specific drafts</div></div></header>
  <div class="toolbar"><input id="search" type="search" placeholder="Find a company" aria-label="Find a company"><select id="stage" aria-label="Next action"><option value="">All next actions</option><option value="review-candidate-fit-and-copy">Review candidate fit</option><option value="verify-employer-opening">Verify opening</option><option value="review-sponsorship-copy">Review sponsorship copy</option><option value="research-sponsorship-contact">Research contact</option><option value="suppressed">Suppressed</option></select></div>
  <p id="count" aria-live="polite"></p>${report.accounts.map(card).join('')}
  <button id="more" type="button">Show more companies</button><p class="limits">Engram handoff is review-only and excludes candidate identities, assessment evidence and message bodies. Public listing status may differ from employer availability.</p></main>
  <script>const cards=[...document.querySelectorAll('article')];let limit=12;function filter(reset=true){if(reset)limit=12;const q=document.querySelector('#search').value.toLowerCase(),s=document.querySelector('#stage').value;let total=0,shown=0;cards.forEach(c=>{const match=c.dataset.company.includes(q)&&(!s||c.dataset.action===s);if(match)total++;c.hidden=!match||shown>=limit;if(!c.hidden)shown++;});document.querySelector('#count').textContent=shown+' of '+total+' '+(total===1?'company':'companies')+' shown';document.querySelector('#more').hidden=shown>=total;}document.querySelector('#search').addEventListener('input',()=>filter());document.querySelector('#stage').addEventListener('change',()=>filter());document.querySelector('#more').addEventListener('click',()=>{limit+=12;filter(false);});document.querySelectorAll('.copy').forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(b.previousElementSibling.textContent);b.textContent='Copied';}catch{b.textContent='Select draft text to copy';}}));filter();</script></body></html>`;
}
